### PR TITLE
Fix Import for using frameworks

### PR DESCRIPTION
**Pull request by kdawgwilk**

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Indeed it fixed the import but now I get `"Duplicate interface definition for class 'NHNetAssociation'"`

**Comment by kdawgwilk** [comment]
The above issue was related to how I was importing in my code so this pull request should be good to go

**Comment by huynguyencong** [comment]
Do you solve the problem? I can't reproduce the bug. Can you tell me how to reproduce?

**Comment by kdawgwilk** [comment]
You need to be using CocoaPods with the `use_frameworks!` option and then it should reproduce the problem

**Comment by huynguyencong** [comment]
I have bug `'NHNetworkTime.h' file not found` when add `use_frameworks!`. I'm trying to fix? Do you have this bug?

**Comment by huynguyencong** [comment]
Fixed it. Please update 1.6 version, and read Readme file in Swift guide. I use `#import <CocoaAsyncSocket/GCDAsyncUdpSocket.h>` instead of your code because it is compatible when Podfile doesn't use `use_frameworks!`

**Pull request closed without merging**
